from pydantic import BaseModel, Field
from typing import List, Dict

class AnalysisResponse(BaseModel):
    prediction: str = Field(..., description="The predicted medical abnormality or condition.")
    confidence: float = Field(..., description="The model's probability score between 0.0 and 1.0.")

class ChatRequest(BaseModel):
    user_message: str = Field(..., description="The current question asked by the user.")
    prediction_context: str = Field(..., description="The clinical abnormality detected by the vision model.")
    confidence_context: float = Field(..., description="The confidence score of the vision model.")
    chat_history: List[Dict[str, str]] = Field(
        default=[], 
        description="Previous message logs structured as [{'role': 'user'|'assistant', 'content': 'text'}]"
    )

class ChatResponse(BaseModel):
    reply: str = Field(..., description="The conversational response generated by the AI model.")